name: Gradle / Validate wrapper

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/gradl–µ-wrapper.jar'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # tag=v1
